export const FETCH_JOB_START = "FETCH_JOB_START";
export const FETCH_JOB_SUCCESS = "FETCH_JOB_SUCCESS";
export const FETCH_JOB_FAIL = "FETCH_JOB_FAIL";

export const SELECT_JOB_START = "FETCH_JOB_START";
export const SELECT_JOB_SUCCESS = "FETCH_JOB_SUCCESS";
export const SELECT_JOB_FAIL = "FETCH_JOB_FAIL";

export const UPDATE_SELECTED_FIELD = "UPDATE_SELECTED_FIELD";
export const HANDLE_ADD_CHIP = "HANDLE_ADD_CHIP";
export const HANDLE_DELETE_CHIP = "HANDLE_DELETE_CHIP";
export const UPDATE_TEXT_EDITOR = "UPDATE_TEXT_EDITOR";
